### ISSUE TITLE
LookupObjects ( at most 1 ) doesn't work for date or datetime field types

### ISSUE THREAD

**Issue by christianjosephvarriale** [elasticio/salesforce-component#111]
### Summary
- The lookupObject.js file currently doesn't differentiate between a date / datetime field and a string. As per the documentation on SOQL queries, date objects should not be enclosed in quotation marks which is why the error above is thrown. When the SOQL query is generated, it is in the form of `"query WHERE 'custom_field__c = '{{date_str}}' "`

I have attached my current solution used for the deleteObject.js code in a screenshot.

### Steps to reproduce
- Select the Salesforce Component function 'Lookup Object ( at most 1 )'
- Select any object and field which is either type date or datetime
- You will receive a similar error after populating the dynamic field with a string whether or not it's in the proper format for an Apex date/datetime field

### Relevant screenshots

![Screenshot from 2020-02-11 12-33-27](https://user-images.githubusercontent.com/37720685/74246839-6ee5d800-4ce5-11ea-9ff3-5b1c38c48ea0.png)
![Screenshot from 2020-02-11 12-42-56](https://user-images.githubusercontent.com/37720685/74246874-7ad19a00-4ce5-11ea-8677-56ddc9661b72.png)
![Screenshot from 2020-02-11 15-46-06](https://user-images.githubusercontent.com/37720685/74247325-2b3f9e00-4ce6-11ea-8c1c-cf97df200826.png)

**Comment by bennmcgregor** [comment]
This has been addressed in this PR: https://github.com/elasticio/salesforce-component/pull/109

**Comment by stas-fomenko** [comment]
@bennmcgregor 
Not sure if `LookupObjects ( at most 1 ) doesn't work for date or datetime field types` bug fix works correctly, I'm still getting the same error for the following input: 
![image](https://user-images.githubusercontent.com/36419533/74825758-26e13980-5313-11ea-9bc5-f47f4d00c6bc.png)

Error thrown:
![image](https://user-images.githubusercontent.com/36419533/74827191-a4a64480-5315-11ea-9d59-88343ac30161.png)
